# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62121daba7dae51ac6a4793b89da3984996e9f2c2ff79b0efdeeec04e8d49f7478bf59c7b52304dbdb18bb4e27d15f0a8021ae39f74255e9b6ef52d8dc7ed6c4

test:
  secret_key_base: 6136d9c318bb7bb0a2859cbed1e1b3d06d404ea508dc3704eb87939929deed9b4edeb3012430d14423087478bcf1106131f3280b8e2d3599218f5d65daaaaf41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
